### ISSUE TITLE
No fetching

### ISSUE THREAD

**Issue by lakano** [edewit/cordova-background-plugin#2]
Hello,

The object exists, I have sucessfully registered, but no logs and my ajax call isn't received. 

In fact, the fetch doesn't seems to be fired by iOS, I'm waiting since 45 minutes right now with my app in background.

I'm under Cordova 5.1 / iOS 8.4

Do this works for anyone please ?

Regards

**Comment by edewit** [comment]
could you try the [aerogear pushplugin](https://github.com/aerogear/aerogear-cordova-push) instead?

**Comment by lakano** [comment]
I used it for the background fetch feature. But as it doesn't seems to works for me, I now use the cordova-plugin-background-fetch  ( https://github.com/christocracy/cordova-plugin-background-fetch )

Regards,

**Comment by edewit** [comment]
okay, the aerogear has support for background fetch as well
